# 34c3ctf 2017 urlstorage
version: "2"

services:

  web:
    build: ""
    image: ctftraining/34c3ctf_2017_urlstorage
    restart: always
    environment:
      - DOMAIN=34c3ctf2017.local.virzz.com
      - FLAG=flag{221CTF!!}
    ports:
      - "22502:80"
